;Media Player
[module/mediaplayer]
type = custom/script
tail = true
exec = ~/.config/polybar/scripts/player.sh
format-foreground = ${colors.mauve}
label-font = 3
click-middle = playerctl play-pause

format-padding = 1
