[module/workspaces]
type = internal/i3
pin-workspaces = true
strip-wsnumbers = false
index-sort = true

format = <label-state> <label-mode>

ws-icon-0 = 1;󰆍
ws-icon-1 = 2;󰈹
ws-icon-2 = 3;󰅩
ws-icon-3 = 4;󰍡
ws-icon-4 = 5;󰝚
ws-icon-default = 󰍹

; Focused workspace
label-focused = %{T1} %index% %icon% %{T-}
label-focused-background = ${colors.mauve}
label-focused-foreground = ${colors.crust}
label-focused-padding = 0

; Unfocused/Occupied workspace
label-unfocused = %{T1} %index% %icon% %{T-}
label-unfocused-background = ${colors.surface0}
label-unfocused-foreground = ${colors.text}
label-unfocused-padding = 0

; Visible workspace (on other monitor)
label-visible = %{T1} %index% %icon% %{T-}
label-visible-background = ${colors.surface1}
label-visible-foreground = ${colors.text}
label-visible-padding = 0

; Urgent workspace
label-urgent = %{T1} %index% %icon% %{T-}
label-urgent-background = ${colors.red}
label-urgent-foreground = ${colors.crust}
label-urgent-padding = 0
